dataset: "LJSpeech"
device: "cuda"
path:
  text_grids_path: "/root/storage/dasha/data/emo-single-speaker/TextGrids"
  raw_path: "/root/storage/dasha/data/emo-single-speaker/wavs"
  preprocessed_path: "/root/storage/dasha/data/emo-single-speaker/preprocessed"
  val_ids_path: "/root/storage/dasha/data/emo-single-speaker/val_names.txt"

preprocessing:
  include_empty_intervals: true
  val_size: 135
  device: "cuda"
  text:
    language: "en"
  audio:
    sampling_rate: 16000
    max_wav_value: 32768.0
  stft:
    filter_length: 512
    hop_length: 128
    win_length: 512
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
