device: "cuda"
path:
  raw_path: "/root/storage/dasha/natasha/aligned_corpus"
  preprocessed_path: "/root/storage/dasha/natasha/preprocessed_data"

preprocessing:
  include_empty_intervals: true
  val_size: 512
  device: "cuda"
  audio:
    sampling_rate: 22050
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
