device: "cuda"
path:
  ckpt_path: "/root/dasha/FastSpeech2/output"
  log_path: "/root/dasha/FastSpeech2/output"
  result_path: "/root/dasha/FastSpeech2/output"
phones_mapping_path: "/root/dasha/mfa/phones_mapping.json"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 100000
